name: CI

env:
  TLVERSION: 2021

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '18 16 * * 5'

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # http://man7.org/linux/man-pages/man1/date.1.html
    - name: Get date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive${{ env.TLVERSION }}-${{ steps.get-date.outputs.date }}
        restore-keys: texlive${{ env.TLVERSION }}-

    - name: Set up TeX Live
      uses: moewew/tex-actions/setup-texlive@main
      with:
        packagelist:
          l3build
          latex-bin
          luahbtex
          tex
          metafont
          mfware
          texlive-scripts
          latex
          amsmath
          graphics
          tools
          latex-bin-dev
          latex-base-dev
          latex-graphics-dev
          latex-tools-dev
          latex-amsmath-dev
          babel
          babel-english
          hyphen-english
          biblatex
          biber
          bibtex
          csquotes
          ec
          cm-super
          etoolbox
          iftex
          hyperref
          atveryend
          infwarerr
          hycolor
          lm
          lm-math
          psnfss
          unicode-math
          xkeyval
          babel-german
          babel-french
          hyphen-german
          hyphen-french
          bera
          dvips
          bookmark
          booktabs
          carlisle
          cleveref
          datetime2
          datetime2-english
          everysel
          environ
          epstopdf-pkg
          fontaxes
          geometry
          hyphenat
          l3experimental
          libertinus
          libertinus-type1
          listings
          ltxdockit
          microtype
          ms
          mweights
          newtx
          oberdiek
          pgf
          pict2e
          ragged2e
          tcolorbox
          tracklang
          trimspaces
          xcolor

    - name: Run tests
      run: l3build check -q -H  --show-log-on-error

  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # http://man7.org/linux/man-pages/man1/date.1.html
    - name: Get date
      id: get-date
      run: |
        echo "::set-output name=date::$(/bin/date -u "+%Y%m%d")"
      shell: bash

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive${{ env.TLVERSION }}-${{ steps.get-date.outputs.date }}
        restore-keys: texlive${{ env.TLVERSION }}-

    - name: Set up TeX Live
      uses: moewew/tex-actions/setup-texlive@main
      with:
        packagelist:
          l3build
          latex-bin
          luahbtex
          tex
          metafont
          mfware
          texlive-scripts
          latex
          amsmath
          graphics
          tools
          latex-bin-dev
          latex-base-dev
          latex-graphics-dev
          latex-tools-dev
          latex-amsmath-dev
          babel
          babel-english
          hyphen-english
          biblatex
          biber
          bibtex
          csquotes
          ec
          cm-super
          etoolbox
          iftex
          hyperref
          atveryend
          infwarerr
          hycolor
          lm
          lm-math
          psnfss
          unicode-math
          xkeyval
          babel-german
          babel-french
          hyphen-german
          hyphen-french
          bera
          dvips
          bookmark
          booktabs
          carlisle
          cleveref
          datetime2
          datetime2-english
          everysel
          environ
          epstopdf-pkg
          fontaxes
          geometry
          hyphenat
          l3experimental
          libertinus
          libertinus-type1
          listings
          ltxdockit
          microtype
          ms
          mweights
          newtx
          oberdiek
          pgf
          pict2e
          ragged2e
          tcolorbox
          tracklang
          trimspaces
          xcolor

    - name: Compile documentation
      run: l3build doc -q -H
