name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive

    - name: Set up TeX Live environment
      run: ./installsupport/install-texlive.sh

    - name: Run tests
      run: l3build check -q -H  --show-log-on-error

  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive

    - name: Set up TeX Live environment
      run: ./installsupport/install-texlive.sh

    - name: Compile documentation
      run: l3build doc -q -H
