name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron:  '18 16 * * 5'

jobs:
  check:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive

    - name: Set up TeX Live environment
      run: . ci/install-texlive.sh

    - name: Run tests
      run: l3build check -q -H  --show-log-on-error

  doc:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/texlive
          ~/.texlive
        key: texlive

    - name: Set up TeX Live environment
      run: . ci/install-texlive.sh

    - name: Compile documentation
      run: l3build doc -q -H
